apiVersion: platform.goldenpath.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: gp-piloto-ensayo
  namespace: equipo-piloto
  labels:
    platform.goldenpath.io/owner: piloto
    platform.goldenpath.io/cost-center: mati-platform
    backstage.io/kubernetes-id: gp-piloto-ensayo
spec:
  size: pequena
